baseURL = "its-hritika.github.io"
title = "Hritika's Portfolio"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2025, Hritika Singh"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = -100
  
# Configuration Features
[params]
  description = "Hritika's Portfolio"      # Your meta description of the site
  header_title = "Hritika Singh"             # Your header title
  header_subtitle = "Penetration Tester & Ethical Hacker | Mumbai, IN" # Your header subtitle
  home_image = "/images/avatar.png"          # Path to header image starting from the static directory (optional)
  recent_posts = 0                           # Max amount of recent posts to show
  mainSections = ["about", "projects"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/its-hritika"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/its-hritika/"
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = "mailto:hritikasingh366@gmail.com"  
